[build]
functions = "netlify/functions"
[context.production]
publish = "./"
[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/index/*"
status = 200
to = "/.netlify/functions/index/:splat"
